name: "Rust release"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      DOCKER_REGISTRY_USER:
        required: false
      DOCKER_REGISTRY_PASSWORD:
        required: false

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - run: ls ~/.cache/go-build
      - run: ls ~/go/pkg/mod

      # - uses: actions/setup-go@v3
      #   with:
      #     go-version: '1.18'

      # - name: Semantic Release
      #   uses: cycjimmy/semantic-release-action@v2
      #   id: semantic
      #   with:
      #     semantic_version: 19.0.2
      #     extra_plugins: |
      #       @semantic-release/exec@6.0
      #       @semantic-release/git@10.0
      #       @codedependant/semantic-release-docker@4.1
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #     DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}
      #     DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
