name: "Node audit"

on:
  workflow_call:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.4
      - uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - run: pnpm audit
