name: "Rust release"

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
      CARGO_REGISTRY_TOKEN:
        required: false
      DOCKER_HUB_USERNAME:
        required: false
      DOCKER_REGISTRY_PASSWORD:
        required: false

env:
  RUST_BACKTRACE: 1

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install semantic-release-rust
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: semantic-release-rust --version 1.0.0-alpha.8

      # The release build is used in the Semantic Release step
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 19.0.2
          extra_plugins: |
            @semantic-release/exec@6.0
            @semantic-release/git@10.0
            @codedependant/semantic-release-docker@4.1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
